### ISSUE TITLE
Xcode Project: Website Segue

### ISSUE THREAD

**Issue by shawnt18** [yvadher/cmpt275App#11]
I'm having problems opening our website from our app simulator. From what I know we have two ways:
1) By tapping on "Help" on MenuWindow, and 2) By tapping on website link in About Page.

I've tried it on the iPhone 8 Plus and on the iPad (5th gen), where they fail to open the webpage.
All it does is minimize the goTalk app.
In the case for iPad, the simulator crashes/is interrupted by an error.

**Comment by yvadher** [comment]
Fixed it. It was problem in web view delegate file.
