### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by shawnt18** [yvadher/cmpt275App#8]
So I tried to login to my goTalk account today but my email was no longer registered.

I registered a new account, but when I went to login, I got an error.
![login error](https://user-images.githubusercontent.com/29647075/33401761-47990fb0-d50f-11e7-8bb2-ea9466f6d1f0.jpeg)
Every time I boot the simulator, it stops and shows me the same error.

I saw in the console log that my login information was correct and the matching JSON was found I the database. I don't know what's going on though.

**Comment by yvadher** [comment]
Was it the problem when you first cloned devYagnik branch? before I pushed my latest commit, It was working fine and was tested by karamveer. Is this error occurring after your commit?
In regards to database, I rested the database so all dummy emails account was gone.

**Comment by shawnt18** [comment]
When i first cloned your devYagnik branch, it was working okay until I tried to sign in.
I guess its fine if its working for you.

**Comment by yvadher** [comment]
Ok I will set up some tests to recreate this problem and will fix it if any bug found.

**Comment by shawnt18** [comment]
In HW4 feedback, we scored 1/5 because prof was "automatically logged in" on app startup. 
That's shouldn't happen now right?

**Comment by yvadher** [comment]
I think professor have mistaken it. May be Fahad can email ta with clarification. Having logged in asap is our app functionality so that unless user logout user does not need to login back. As the controller by fahad was not done before version 2 so we could not implement the logout button functionality.

**Comment by shawnt18** [comment]
Yeah the TA might've been misunderstood when testing it.
But if the app boots up the first time and is automatically sent to the main screen, then we're in trouble lol.
If the app is ok now, then that's great.

**Comment by yvadher** [comment]
It never worked like that. The reason behind the app to go to main screen could be that TA is using the same computer from our version 1 and also for version 2. So the user login information is stored in the phone and its not been cleared up, which could done by logging out or calling a command from terminal.

**Comment by yvadher** [comment]
I have fixed the back-end. So now error on first login wont show up. :)
